// Generated by gencpp from file beginner_tutorials/add_two_ints.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INTS_H
#define BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INTS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/add_two_intsRequest.h>
#include <beginner_tutorials/add_two_intsResponse.h>


namespace beginner_tutorials
{

struct add_two_ints
{

typedef add_two_intsRequest Request;
typedef add_two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_ints
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::add_two_ints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::add_two_ints&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::add_two_ints > {
  static const char* value()
  {
    return "beginner_tutorials/add_two_ints";
  }

  static const char* value(const ::beginner_tutorials::add_two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::add_two_intsRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_ints >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_ints >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_intsRequest> should match
// service_traits::DataType< ::beginner_tutorials::add_two_ints >
template<>
struct DataType< ::beginner_tutorials::add_two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_ints >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::add_two_intsResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::add_two_ints >
template<>
struct MD5Sum< ::beginner_tutorials::add_two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::add_two_ints >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::add_two_intsResponse> should match
// service_traits::DataType< ::beginner_tutorials::add_two_ints >
template<>
struct DataType< ::beginner_tutorials::add_two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::add_two_ints >::value();
  }
  static const char* value(const ::beginner_tutorials::add_two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADD_TWO_INTS_H
