; Auto-generated. Do not edit!


(cl:in-package chores-msg)


;//! \htmlinclude do_dishesResult.msg.html

(cl:defclass <do_dishesResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:integer
    :initform 0))
)

(cl:defclass do_dishesResult (<do_dishesResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <do_dishesResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'do_dishesResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name chores-msg:<do_dishesResult> is deprecated: use chores-msg:do_dishesResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <do_dishesResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader chores-msg:total_dishes_cleaned-val is deprecated.  Use chores-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <do_dishesResult>) ostream)
  "Serializes a message object of type '<do_dishesResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <do_dishesResult>) istream)
  "Deserializes a message object of type '<do_dishesResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<do_dishesResult>)))
  "Returns string type for a message object of type '<do_dishesResult>"
  "chores/do_dishesResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'do_dishesResult)))
  "Returns string type for a message object of type 'do_dishesResult"
  "chores/do_dishesResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<do_dishesResult>)))
  "Returns md5sum for a message object of type '<do_dishesResult>"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'do_dishesResult)))
  "Returns md5sum for a message object of type 'do_dishesResult"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<do_dishesResult>)))
  "Returns full string definition for message of type '<do_dishesResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'do_dishesResult)))
  "Returns full string definition for message of type 'do_dishesResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <do_dishesResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <do_dishesResult>))
  "Converts a ROS message object to a list"
  (cl:list 'do_dishesResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
