; Auto-generated. Do not edit!


(cl:in-package chores-msg)


;//! \htmlinclude do_dishesGoal.msg.html

(cl:defclass <do_dishesGoal> (roslisp-msg-protocol:ros-message)
  ((dishwasher_id
    :reader dishwasher_id
    :initarg :dishwasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass do_dishesGoal (<do_dishesGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <do_dishesGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'do_dishesGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name chores-msg:<do_dishesGoal> is deprecated: use chores-msg:do_dishesGoal instead.")))

(cl:ensure-generic-function 'dishwasher_id-val :lambda-list '(m))
(cl:defmethod dishwasher_id-val ((m <do_dishesGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader chores-msg:dishwasher_id-val is deprecated.  Use chores-msg:dishwasher_id instead.")
  (dishwasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <do_dishesGoal>) ostream)
  "Serializes a message object of type '<do_dishesGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <do_dishesGoal>) istream)
  "Deserializes a message object of type '<do_dishesGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<do_dishesGoal>)))
  "Returns string type for a message object of type '<do_dishesGoal>"
  "chores/do_dishesGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'do_dishesGoal)))
  "Returns string type for a message object of type 'do_dishesGoal"
  "chores/do_dishesGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<do_dishesGoal>)))
  "Returns md5sum for a message object of type '<do_dishesGoal>"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'do_dishesGoal)))
  "Returns md5sum for a message object of type 'do_dishesGoal"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<do_dishesGoal>)))
  "Returns full string definition for message of type '<do_dishesGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'do_dishesGoal)))
  "Returns full string definition for message of type 'do_dishesGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <do_dishesGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <do_dishesGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'do_dishesGoal
    (cl:cons ':dishwasher_id (dishwasher_id msg))
))
