// Generated by gencpp from file hrwros_msgs/meters_2_feetRequest.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_METERS_2_FEETREQUEST_H
#define HRWROS_MSGS_MESSAGE_METERS_2_FEETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct meters_2_feetRequest_
{
  typedef meters_2_feetRequest_<ContainerAllocator> Type;

  meters_2_feetRequest_()
    : measurement_meters(0.0)  {
    }
  meters_2_feetRequest_(const ContainerAllocator& _alloc)
    : measurement_meters(0.0)  {
  (void)_alloc;
    }



   typedef double _measurement_meters_type;
  _measurement_meters_type measurement_meters;





  typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct meters_2_feetRequest_

typedef ::hrwros_msgs::meters_2_feetRequest_<std::allocator<void> > meters_2_feetRequest;

typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetRequest > meters_2_feetRequestPtr;
typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetRequest const> meters_2_feetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.measurement_meters == rhs.measurement_meters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator1> & lhs, const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "233a71c3d9ce741eb27d4a8459bfbe49";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x233a71c3d9ce741eULL;
  static const uint64_t static_value2 = 0xb27d4a8459bfbe49ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/meters_2_feetRequest";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 measurement_meters # Request field\n"
;
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.measurement_meters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct meters_2_feetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::meters_2_feetRequest_<ContainerAllocator>& v)
  {
    s << indent << "measurement_meters: ";
    Printer<double>::stream(s, indent + "  ", v.measurement_meters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_METERS_2_FEETREQUEST_H
