// Generated by gencpp from file hrwros_msgs/meters_2_feetResponse.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_METERS_2_FEETRESPONSE_H
#define HRWROS_MSGS_MESSAGE_METERS_2_FEETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct meters_2_feetResponse_
{
  typedef meters_2_feetResponse_<ContainerAllocator> Type;

  meters_2_feetResponse_()
    : measurement_feet(0.0)
    , success(false)  {
    }
  meters_2_feetResponse_(const ContainerAllocator& _alloc)
    : measurement_feet(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _measurement_feet_type;
  _measurement_feet_type measurement_feet;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct meters_2_feetResponse_

typedef ::hrwros_msgs::meters_2_feetResponse_<std::allocator<void> > meters_2_feetResponse;

typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetResponse > meters_2_feetResponsePtr;
typedef boost::shared_ptr< ::hrwros_msgs::meters_2_feetResponse const> meters_2_feetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator1> & lhs, const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.measurement_feet == rhs.measurement_feet &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator1> & lhs, const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e0416bc97b432dc446977a012d0589e";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e0416bc97b432dcULL;
  static const uint64_t static_value2 = 0x446977a012d0589eULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/meters_2_feetResponse";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 measurement_feet   # Response field\n"
"bool success\n"
;
  }

  static const char* value(const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.measurement_feet);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct meters_2_feetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::meters_2_feetResponse_<ContainerAllocator>& v)
  {
    s << indent << "measurement_feet: ";
    Printer<double>::stream(s, indent + "  ", v.measurement_feet);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_METERS_2_FEETRESPONSE_H
