// Generated by gencpp from file hrwros_msgs/meters_2_feet.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_METERS_2_FEET_H
#define HRWROS_MSGS_MESSAGE_METERS_2_FEET_H

#include <ros/service_traits.h>


#include <hrwros_msgs/meters_2_feetRequest.h>
#include <hrwros_msgs/meters_2_feetResponse.h>


namespace hrwros_msgs
{

struct meters_2_feet
{

typedef meters_2_feetRequest Request;
typedef meters_2_feetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct meters_2_feet
} // namespace hrwros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hrwros_msgs::meters_2_feet > {
  static const char* value()
  {
    return "d1036d55dafbbfcc5e557511312e2fdf";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feet&) { return value(); }
};

template<>
struct DataType< ::hrwros_msgs::meters_2_feet > {
  static const char* value()
  {
    return "hrwros_msgs/meters_2_feet";
  }

  static const char* value(const ::hrwros_msgs::meters_2_feet&) { return value(); }
};


// service_traits::MD5Sum< ::hrwros_msgs::meters_2_feetRequest> should match
// service_traits::MD5Sum< ::hrwros_msgs::meters_2_feet >
template<>
struct MD5Sum< ::hrwros_msgs::meters_2_feetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::meters_2_feet >::value();
  }
  static const char* value(const ::hrwros_msgs::meters_2_feetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::meters_2_feetRequest> should match
// service_traits::DataType< ::hrwros_msgs::meters_2_feet >
template<>
struct DataType< ::hrwros_msgs::meters_2_feetRequest>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::meters_2_feet >::value();
  }
  static const char* value(const ::hrwros_msgs::meters_2_feetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hrwros_msgs::meters_2_feetResponse> should match
// service_traits::MD5Sum< ::hrwros_msgs::meters_2_feet >
template<>
struct MD5Sum< ::hrwros_msgs::meters_2_feetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hrwros_msgs::meters_2_feet >::value();
  }
  static const char* value(const ::hrwros_msgs::meters_2_feetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hrwros_msgs::meters_2_feetResponse> should match
// service_traits::DataType< ::hrwros_msgs::meters_2_feet >
template<>
struct DataType< ::hrwros_msgs::meters_2_feetResponse>
{
  static const char* value()
  {
    return DataType< ::hrwros_msgs::meters_2_feet >::value();
  }
  static const char* value(const ::hrwros_msgs::meters_2_feetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_METERS_2_FEET_H
